name: Ruby

on:
  pull_request:
    branches:
      - "*"
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

env:
  COVERAGE: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.4'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Rubocop && RSpec
      run: bundle exec rake
